version: '2'
services:

  traefik:
    image: traefik:v1.7.4-alpine
    hostname: traefik.lab.com
    environment:
      TZ: Europe/Paris
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --logLevel='DEBUG'
      --api.dashboard=true
      --InsecureSkipVerify=true
      --entryPoints='Name:http Address::80 Redirect.EntryPoint:https'
      --entryPoints='Name:https Address::443 TLS'
      --defaultentrypoints='http,https'
      --docker
      --docker.exposedbydefault=true
      --docker.watch=true
      --docker.swarmmode=false
      --docker.endpoint='unix:///var/run/docker.sock'
    networks:
      auth_net:
      service_net:
      infra_net:
        ipv4_address: 192.168.111.10
    labels:
      traefik.enable: true
  
  keycloak_db:
    image: postgres:11.2-alpine
    environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=password
        - POSTGRES_ROOT_PASSWORD=password
    networks:
      auth_net:
    ports:
      - "5432:5432"
    volumes:
      - keycloak_db_data_vol:/var/lib/postgresql/data
      - ./config/db:/docker-entrypoint-initdb.d
    labels:
      - "traefik.enable=false"

  keycloak:
    image: jboss/keycloak:7.0.1
    hostname: keycloak
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak_db
      - DB_DATABASE=keycloak
      - DB_PORT=5432
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=password
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_LOGLEVEL=INFO
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
    networks:
      auth_net:
    depends_on:
      - traefik
      - keycloak_db
    labels:
      - traefik.port=8443
      - traefik.frontend.rule=Host:auth.lab.com
      - traefik.protocol=https
    command: ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.docker=enabled"]
  
  keycloak-gatekeeper:
    image: quay.io/keycloak/keycloak-gatekeeper:7.0.1
    labels:
     - "traefik.port=3000"
     - "traefik.frontend.rule=Host:service1.lab.com"
     - "traefik.protocol=http"
    restart: always
    depends_on:
     - keycloak
    networks:
      service_net:
    external_links:
      - traefik:auth.lab.com
    volumes:
      - ./keycloak-gatekeeper/keycloak-gatekeeper.conf:/etc/keycloak-gatekeeper.conf
    entrypoint:
      - /opt/keycloak-gatekeeper
      - --config=/etc/keycloak-gatekeeper.conf
  
  service_1:
    image: containous/whoami
    networks:
      service_net:
      infra_net:
        ipv4_address: 192.168.111.101
    depends_on:
      - traefik
    labels:
      - "traefik.enable=false"

  service_2:
    image: containous/whoami
    networks:
      infra_net:
        ipv4_address: 192.168.111.102
    depends_on:
      - traefik
    labels:
     - "traefik.port=80"
     - "traefik.frontend.rule=Host:service2.lab.com"
     - "traefik.protocol=http"

  dnsmasq:
    container_name: dnsmasq
    hostname: dnsmasq
    image: andyshinn/dnsmasq
    command: [
      '--no-daemon',
      '--log-queries',
      '--domain-needed',
      '--bogus-priv',
      '--strict-order',
      '--expand-hosts',
      '--domain=lab.com',
      '--server=/lab.com/8.8.8.8',
      '--host-record=svc1.lab.com,192.168.111.101',
      '--host-record=svc2.lab.com,192.168.111.102',
      '--host-record=auth.lab.com,192.168.111.10',
      '--host-record=service1.lab.com,192.168.111.10',
      '--host-record=service2.lab.com,192.168.111.10',
      '--mx-host=www.lab.com,192.168.111.10,10',
      '--address=/lab.com/::'
    ]
    expose:
      - "53/tcp"
      - "53/udp"
    cap_add:
      - NET_ADMIN
    networks:
      infra_net:
        ipv4_address: 192.168.111.2

  squid:
    container_name: squid
    hostname: squid
    image: sameersbn/squid:latest
    ports:
      - "3128:3128"
    volumes:
      - ./config/squid.conf:/etc/squid/squid.conf:ro
      - ./config/resolv.conf:/etc/resolv.conf:ro
    depends_on:
      - dnsmasq
    networks:
      infra_net:
        ipv4_address: 192.168.111.3


networks:
  service_net:
  auth_net:
  infra_net:
    driver: bridge
    # enable_ipv6: true
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.111.0/24


volumes: 
  keycloak_db_data_vol:
